version: "3.8"

networks:
  shared-net:
    external: true

services:
  order-db:
    image: postgres:14
    container_name: order-db
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order
      POSTGRES_DB: orderdb
    ports:
      - "5433:5432"
    networks:
      - shared-net

  order-service:
    build:
      context: .
    container_name: order-service
    depends_on:
      - order-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=order
      - SPRING_DATASOURCE_PASSWORD=order
    ports:
      - "8090:8090"
    networks:
      - shared-net

